boot.o: boot.S multiboot.h x86_desc.h types.h
common_asm_link.o: common_asm_link.S common_asm_link.h
x86_desc.o: x86_desc.S x86_desc.h types.h
filesys.o: filesys.c filesys.h lib.h types.h
i8259.o: i8259.c i8259.h types.h lib.h
idt.o: idt.c idt.h x86_desc.h types.h lib.h common_asm_link.h keyboard.h \
  rtc.h i8259.h
kernel.o: kernel.c multiboot.h types.h x86_desc.h lib.h i8259.h debug.h \
  tests.h idt.h rtc.h keyboard.h paging.h filesys.h
keyboard.o: keyboard.c keyboard.h lib.h types.h i8259.h terminal.h
lib.o: lib.c lib.h types.h
paging.o: paging.c paging.h types.h x86_desc.h lib.h
rtc.o: rtc.c rtc.h types.h lib.h i8259.h
terminal.o: terminal.c terminal.h types.h keyboard.h lib.h
tests.o: tests.c tests.h x86_desc.h types.h lib.h rtc.h i8259.h \
  keyboard.h terminal.h filesys.h
